package pt.reditus.pocsiops.core;
// Generated Sep 7, 2016 11:27:49 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Operations generated by hbm2java
 */
@Entity
@Table(name = "OPERATIONS")
public class Operations implements java.io.Serializable {

	private int idOperations;
	private Serializable name;
	private int timeLimit;
	private Serializable type;
	private Set<OperatorOperation> operatorOperations = new HashSet<OperatorOperation>(0);

	public Operations() {
	}

	public Operations(int idOperations, Serializable name, int timeLimit) {
		this.idOperations = idOperations;
		this.name = name;
		this.timeLimit = timeLimit;
	}

	public Operations(int idOperations, Serializable name, int timeLimit, Serializable type,
			Set<OperatorOperation> operatorOperations) {
		this.idOperations = idOperations;
		this.name = name;
		this.timeLimit = timeLimit;
		this.type = type;
		this.operatorOperations = operatorOperations;
	}

	@Id

	@Column(name = "ID_OPERATIONS", unique = true, nullable = false)
	public int getIdOperations() {
		return this.idOperations;
	}

	public void setIdOperations(int idOperations) {
		this.idOperations = idOperations;
	}

	@Column(name = "NAME", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "TIME_LIMIT", nullable = false)
	public int getTimeLimit() {
		return this.timeLimit;
	}

	public void setTimeLimit(int timeLimit) {
		this.timeLimit = timeLimit;
	}

	@Column(name = "TYPE")
	public Serializable getType() {
		return this.type;
	}

	public void setType(Serializable type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operations")
	public Set<OperatorOperation> getOperatorOperations() {
		return this.operatorOperations;
	}

	public void setOperatorOperations(Set<OperatorOperation> operatorOperations) {
		this.operatorOperations = operatorOperations;
	}

}
