package pt.reditus.pocsiops.core;
// Generated Sep 7, 2016 11:27:49 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * States generated by hbm2java
 */
@Entity
@Table(name = "STATES")
public class States implements java.io.Serializable {

	private int idState;
	private String name;
	private String description;
	private Set<OperatorOperation> operatorOperations = new HashSet<OperatorOperation>(0);

	public States() {
	}

	public States(int idState, String name) {
		this.idState = idState;
		this.name = name;
	}

	public States(int idState, String name, String description, Set<OperatorOperation> operatorOperations) {
		this.idState = idState;
		this.name = name;
		this.description = description;
		this.operatorOperations = operatorOperations;
	}

	@Id

	@Column(name = "ID_STATE", unique = true, nullable = false)
	public int getIdState() {
		return this.idState;
	}

	public void setIdState(int idState) {
		this.idState = idState;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "states")
	public Set<OperatorOperation> getOperatorOperations() {
		return this.operatorOperations;
	}

	public void setOperatorOperations(Set<OperatorOperation> operatorOperations) {
		this.operatorOperations = operatorOperations;
	}

}
