package pt.reditus.pocsiops.core;
// Generated Sep 7, 2016 11:27:49 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "USERS")
public class Users implements java.io.Serializable {

	private int idUser;
	private Serializable username;
	private Serializable password;

	public Users() {
	}

	public Users(int idUser, Serializable username, Serializable password) {
		this.idUser = idUser;
		this.username = username;
		this.password = password;
	}

	@Id

	@Column(name = "ID_USER", unique = true, nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "USERNAME", nullable = false)
	public Serializable getUsername() {
		return this.username;
	}

	public void setUsername(Serializable username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false)
	public Serializable getPassword() {
		return this.password;
	}

	public void setPassword(Serializable password) {
		this.password = password;
	}

}
